repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Run ruff format with uv
        entry: uv run ruff format
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: ruff-check
        name: Run ruff check with uv
        entry: uv run ruff check
        language: system
        types: [python]